spring.application.name=notification-service

# Use environment variables if set (via Docker), fallback to local names/ports
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:guest}

# PostgreSQL Database Settings
spring.datasource.url=jdbc:postgresql://${SPRING_DATASOURCE_HOST:localhost}:5432/postgres
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:pgAdmin4}

# This tells Spring to automatically build our SQL tables for us!
spring.jpa.hibernate.ddl-auto=update

# Expose health and info endpoints to the web
management.endpoints.web.exposure.include=health,info,metrics
# Show full details instead of just "UP"
management.endpoint.health.show-details=always

# Add this line to explicitly tell Hibernate what database you are using
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect