spring.application.name=notification-service

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# PostgreSQL Database Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=pgAdmin4

# This tells Spring to automatically build our SQL tables for us!
spring.jpa.hibernate.ddl-auto=update